apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrast-agent-operator
  namespace: contrast-agent-operator
spec:
  template:
    spec:
      containers:
        - name: contrast-agent-operator
          env:
            - name: CONTRAST_EVENT_QUEUE_MERGE_WINDOW_SECONDS
              value: "1"
