namespace: super-awesome-app-qa

bases:
  - ../all

patches:
  - target:
      kind: Service
      name: webgoat-net
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30083
