resources:
- base/namespace.yaml
- base/netflicks-net-deployment.yaml
- base/netflicks-net-injector.yaml
- base/netflicks-net-service.yaml
- base/petclinic-java-deployment.yaml
- base/petclinic-java-injector.yaml
