namespace: super-awesome-app-prod

bases:
  - ../all

patches:
  - target:
      kind: Service
      name: netflicks-net
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30084
