apiVersion: v1
kind: Service
metadata:
  name: netflicks-net
spec:
  ports:
    - name: http
      nodePort: 30083
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: netflicks-net
  type: NodePort
