apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-java
  labels:
    app.kubernetes.io/name: petclinic-java
    contrast/inject: java
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: petclinic-java
  template:
    metadata:
      labels:
        app.kubernetes.io/name: petclinic-java
    spec:
      containers:
        - image: contrastsecuritydemo/spring-petclinic:1.5.1
          name: app
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 30
            periodSeconds: 3
            initialDelaySeconds: 30
          resources:
            limits:
              cpu: '1'
              memory: 1024M
