apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-net
  labels:
    app.kubernetes.io/name: webgoat-net
    contrast/inject: dotnet-core
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: webgoat-net
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webgoat-net
    spec:
      containers:
        - image: contrastsecuritydemo/netflicks:1.0
          name: app
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ConnectionStrings__DotNetFlicksConnection
              value: "Server=tcp:localhost,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;"
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: 1024M
        - name: netflicks-db
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "reallyStrongPwd123"
          resources:
            limits:
              cpu: '1'
              memory: 2048M
