apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-net
  labels:
    app.kubernetes.io/name: webgoat-net
    contrast/inject: dotnet-core
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: webgoat-net
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webgoat-net
    spec:
      containers:
        - image: ghcr.io/contrast-security-oss/webgoat.net:latest
          name: app
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: 1024M
