apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-awesome-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Contrast-Security-OSS/agent-operator-demo.git
    targetRevision: HEAD
    path: src/workloads/super-awesome-app/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-awesome-app-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Contrast-Security-OSS/agent-operator-demo.git
    targetRevision: HEAD
    path: src/workloads/super-awesome-app/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: default
